AWSTemplateFormatVersion: '2010-09-09'
Description: Saves a record to Route53 hosted zone for cloudfront

Parameters:
  EnvName:
    Type: String
  TypeProject:
    Type: String
  HostedZoneId:
    Type: String
  DnsName:
    Type: String

Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Sub ${HostedZoneId}
      RecordSets:
        - Name: !Sub ${DnsName}
          Type: CNAME
          TTL: 60
          ResourceRecords:
            - 'Fn::ImportValue': !Sub '${EnvName}-${TypeProject}-CfnDistribution'